// examples/react/BukaViewerComponent.jsx
import React, { useCallback, useEffect, useRef, useState } from 'react';
import { BukaViewer, EVENTS } from '../../src/core/index.js';
import '../../src/renderers/pdf.js';

const BukaViewerComponent = ({ 
  source, 
  options = {}, 
  onDocumentLoaded,
  onPageChanged,
  onZoomChanged,
  onSearchResult,
  onAnnotationAdded,
  onError
}) => {
  const containerRef = useRef(null);
  const viewerRef = useRef(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const [documentInfo, setDocumentInfo] = useState(null);

  // Default options
  const defaultOptions = {
    enableAnnotations: true,
    enableSearch: true,
    enableThumbnails: true,
    enableToolbar: true,
    enableCache: true,
    ...options
  };

  // Initialize viewer
  useEffect(() => {
    if (!containerRef.current) return;

    try {
      viewerRef.current = new BukaViewer(containerRef.current, defaultOptions);
      
      // Set up event listeners
      const viewer = viewerRef.current;

      viewer.on(EVENTS.DOCUMENT_LOADED, (data) => {
        setDocumentInfo(data);
        setIsLoading(false);
        setError(null);
        onDocumentLoaded?.(data);
      });

      viewer.on(EVENTS.PAGE_CHANGED, (data) => {
        onPageChanged?.(data);
      });

      viewer.on(EVENTS.ZOOM_CHANGED, (data) => {
        onZoomChanged?.(data);
      });

      viewer.on(EVENTS.SEARCH_RESULT, (data) => {
        onSearchResult?.(data);
      });

      viewer.on(EVENTS.ANNOTATION_ADDED, (data) => {
        onAnnotationAdded?.(data);
      });

      viewer.on(EVENTS.ERROR, (error) => {
        setError(error.message || error.toString());
        setIsLoading(false);
        onError?.(error);
      });

    } catch (error) {
      console.error('Failed to initialize BukaViewer:', error);
      setError('Failed to initialize document viewer');
    }

    // Cleanup
    return () => {
      if (viewerRef.current) {
        viewerRef.current.destroy();
        viewerRef.current = null;
      }
    };
  }, []);

  // Load document when source changes
  useEffect(() => {
    if (!viewerRef.current || !source) return;

    const loadDocument = async () => {
      try {
        setIsLoading(true);
        setError(null);
        await viewerRef.current.load(source);
      } catch (error) {
        console.error('Failed to load document:', error);
        setError(error.message || 'Failed to load document');
        setIsLoading(false);
      }
    };

    loadDocument();
  }, [source]);

  // Public API methods
  const goToPage = useCallback((page) => {
    if (viewerRef.current) {
      return viewerRef.current.currentRenderer?.goto(page);
    }
    return false;
  }, []);

  const setZoom = useCallback((zoom) => {
    if (viewerRef.current) {
      return viewerRef.current.currentRenderer?.zoom(zoom);
    }
  }, []);

  const search = useCallback((query) => {
    if (viewerRef.current) {
      return viewerRef.current.currentRenderer?.search(query);
    }
    return [];
  }, []);

  const addAnnotation = useCallback((annotation) => {
    if (viewerRef.current) {
      return viewerRef.current.addAnnotation(annotation);
    }
    return null;
  }, []);

  const exportAnnotations = useCallback(() => {
    if (viewerRef.current) {
      return viewerRef.current.exportAnnotations();
    }
    return [];
  }, []);

  // Expose methods via ref (for imperative usage)
  React.useImperativeHandle(containerRef, () => ({
    goToPage,
    setZoom,
    search,
    addAnnotation,
    exportAnnotations,
    getCurrentPage: () => viewerRef.current?.getCurrentPage(),
    getTotalPages: () => viewerRef.current?.getTotalPages(),
    getZoom: () => viewerRef.current?.getZoom(),
    viewer: viewerRef.current
  }), [goToPage, setZoom, search, addAnnotation, exportAnnotations]);

  return (
    <div style={{ width: '100%', height: '100%', position: 'relative' }}>
      {isLoading && (
        <div style={{
          position: 'absolute',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          backgroundColor: 'rgba(255, 255, 255, 0.8)',
          zIndex: 1000
        }}>
          <div>Loading document...</div>
        </div>
      )}
      
      {error && (
        <div style={{
          position: 'absolute',
          top: 10,
          left: 10,
          right: 10,
          backgroundColor: '#f8d7da',
          color: '#721c24',
          padding: '10px',
          borderRadius: '4px',
          border: '1px solid #f5c6cb',
          zIndex: 1001
        }}>
          Error: {error}
          <button 
            onClick={() => setError(null)}
            style={{
              float: 'right',
              background: 'none',
              border: 'none',
              color: '#721c24',
              cursor: 'pointer',
              fontSize: '16px'
            }}
          >
            ×
          </button>
        </div>
      )}
      
      <div 
        ref={containerRef}
        style={{ 
          width: '100%', 
          height: '100%',
          opacity: error ? 0.5 : 1
        }} 
      />
    </div>
  );
};

export default BukaViewerComponent;

// examples/vue/BukaViewerComponent.vue
<template>
  <div class="buka-viewer-wrapper">
    <!-- Loading overlay -->
    <div v-if="isLoading" class="loading-overlay">
      <div class="loading-spinner">Loading document...</div>
    </div>
    
    <!-- Error display -->
    <div v-if="error" class="error-overlay">
      <div class="error-message">
        Error: {{ error }}
        <button @click="error = null" class="close-btn">×</button>
      </div>
    </div>
    
    <!-- Viewer container -->
    <div 
      ref="containerRef"
      class="buka-viewer-container"
      :class="{ 'has-error': error }"
    />
  </div>
</template>

<script>
import { ref, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { BukaViewer, EVENTS } from '../../src/core/index.js'
import '../../src/renderers/pdf.js' // Ensure PDF renderer is registered

export default {
  name: 'BukaViewerComponent',
  props: {
    source: {
      type: [String, File, Blob],
      default: null
    },
    options: {
      type: Object,
      default: () => ({})
    }
  },
  emits: [
    'document-loaded',
    'page-changed', 
    'zoom-changed',
    'search-result',
    'annotation-added',
    'error'
  ],
  setup(props, { emit, expose }) {
    const containerRef = ref(null)
    const viewer = ref(null)
    const isLoading = ref(false)
    const error = ref(null)
    const documentInfo = ref(null)

    // Default options
    const defaultOptions = {
      enableAnnotations: true,
      enableSearch: true,
      enableThumbnails: true,
      enableToolbar: true,
      enableCache: true,
      ...props.options
    }

    // Initialize viewer
    const initViewer = async () => {
      if (!containerRef.value) return

      try {
        viewer.value = new BukaViewer(containerRef.value, defaultOptions)
        
        // Set up event listeners
        viewer.value.on(EVENTS.DOCUMENT_LOADED, (data) => {
          documentInfo.value = data
          isLoading.value = false
          error.value = null
          emit('document-loaded', data)
        })

        viewer.value.on(EVENTS.PAGE_CHANGED, (data) => {
          emit('page-changed', data)
        })

        viewer.value.on(EVENTS.ZOOM_CHANGED, (data) => {
          emit('zoom-changed', data)
        })

        viewer.value.on(EVENTS.SEARCH_RESULT, (data) => {
          emit('search-result', data)
        })

        viewer.value.on(EVENTS.ANNOTATION_ADDED, (data) => {
          emit('annotation-added', data)
        })

        viewer.value.on(EVENTS.ERROR, (errorData) => {
          error.value = errorData.message || errorData.toString()
          isLoading.value = false
          emit('error', errorData)
        })

      } catch (err) {
        console.error('Failed to initialize BukaViewer:', err)
        error.value = 'Failed to initialize document viewer'
      }
    }

    // Load document
    const loadDocument = async (source) => {
      if (!viewer.value || !source) return

      try {
        isLoading.value = true
        error.value = null
        await viewer.value.load(source)
      } catch (err) {
        console.error('Failed to load document:', err)
        error.value = err.message || 'Failed to load document'
        isLoading.value = false
      }
    }

    // Public API methods
    const goToPage = (page) => {
      if (viewer.value?.currentRenderer) {
        return viewer.value.currentRenderer.goto(page)
      }
      return false
    }

    const setZoom = (zoom) => {
      if (viewer.value?.currentRenderer) {
        return viewer.value.currentRenderer.zoom(zoom)
      }
    }

    const search = (query) => {
      if (viewer.value?.currentRenderer) {
        return viewer.value.currentRenderer.search(query)
      }
      return []
    }

    const addAnnotation = (annotation) => {
      if (viewer.value) {
        return viewer.value.addAnnotation(annotation)
      }
      return null
    }

    const exportAnnotations = () => {
      if (viewer.value) {
        return viewer.value.exportAnnotations()
      }
      return []
    }

    const getCurrentPage = () => {
      return viewer.value?.getCurrentPage() || 1
    }

    const getTotalPages = () => {
      return viewer.value?.getTotalPages() || 1
    }

    const getZoom = () => {
      return viewer.value?.getZoom() || 1.0
    }

    // Expose methods to parent
    expose({
      goToPage,
      setZoom,
      search,
      addAnnotation,
      exportAnnotations,
      getCurrentPage,
      getTotalPages,
      getZoom,
      viewer
    })

    // Lifecycle hooks
    onMounted(async () => {
      await nextTick()
      await initViewer()
    })

    onUnmounted(() => {
      if (viewer.value) {
        viewer.value.destroy()
        viewer.value = null
      }
    })

    // Watch for source changes
    watch(() => props.source, (newSource) => {
      if (newSource) {
        loadDocument(newSource)
      }
    }, { immediate: true })

    return {
      containerRef,
      isLoading,
      error,
      documentInfo,
      // Methods for template usage
      goToPage,
      setZoom,
      search,
      addAnnotation,
      exportAnnotations
    }
  }
}
</script>

<style scoped>
.buka-viewer-wrapper {
  position: relative;
  width: 100%;
  height: 100%;
}

.buka-viewer-container {
  width: 100%;
  height: 100%;
}

.buka-viewer-container.has-error {
  opacity: 0.5;
}

.loading-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(255, 255, 255, 0.8);
  z-index: 1000;
}

.loading-spinner {
  padding: 20px;
  background: white;
  border-radius: 8px;
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.error-overlay {
  position: absolute;
  top: 10px;
  left: 10px;
  right: 10px;
  z-index: 1001;
}

.error-message {
  background-color: #f8d7da;
  color: #721c24;
  padding: 10px;
  border-radius: 4px;
  border: 1px solid #f5c6cb;
  position: relative;
}

.close-btn {
  position: absolute;
  right: 10px;
  top: 50%;
  transform: translateY(-50%);
  background: none;
  border: none;
  color: #721c24;
  cursor: pointer;
  font-size: 16px;
  font-weight: bold;
}

.close-btn:hover {
  opacity: 0.7;
}
</style>
